version: '3.8'

services:
  llm-document-processor:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BEARER_TOKEN=60359a637b23864b320999e8d98517f239970ee339c266bde110414ce8fb9ed1
    volumes:
      - ./vector_store:/app/vector_store
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
