[build]
  functions = "netlify/functions"
  command = "python build.py"
  publish = "dist"

[build.environment]
  PYTHON_VERSION = "3.11"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main/:splat"
  status = 200
