[build]
  functions = "netlify/functions"
  command = "python -m pip install --upgrade pip && pip install -r requirements.txt"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.11"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main/:splat"
  status = 200
