services:
  - type: web
    name: hackrx-llm-processor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    region: oregon
    healthCheckPath: /health
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: DEBUG
        value: false
      - key: GEMINI_API_KEY
        sync: false
      - key: BEARER_TOKEN
        value: 60359a637b23864b320999e8d98517f239970ee339c266bde110414ce8fb9ed1
